# Generated by Django 5.2.11 on 2026-02-21 10:56

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(db_index=True, max_length=100)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('slide_number', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('private_user', 'Slide'), ('transcript', 'Transcript')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='lectures.lecture')),
            ],
            options={
                'indexes': [models.Index(fields=['lecture', 'source_type'], name='vectorstore_lecture_9b278c_idx'), models.Index(fields=['slide_number'], name='vectorstore_slide_n_fd8054_idx')],
            },
        ),
    ]
