# Generated by Django 5.2.11 on 2026-02-16 16:11

import django.contrib.postgres.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VectorChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='private', max_length=100)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField()),
                ('slide_number', models.IntegerField()),
                ('slide_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('source_type', models.CharField(default='private_user', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['chunk_text'], name='chunk_text_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
